import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { DataTableComponent } from '../../shared/data-table/data-table.component';
import { AdminApiService, ChequeAnalyticsFilters, SoldDishAnalyticsQuery, SoldDishReport } from '../../core/api/admin-api.service';
import { LanguageService } from '../../core/i18n/language.service';

const EMPTY_FILTERS: ChequeAnalyticsFilters = { halls: [], staff: [], businessDays: [], defaultBusinessDayId: null };
const EMPTY_REPORT: SoldDishReport = { filters: { businessDayId: null, from: null, to: null }, items: [], payments: [], summary: { chequeCount: 0, subtotal: 0, discount: 0, serviceFee: 0, total: 0, vatRate: 18, vatAmount: 0, amountExcludingVat: 0 } };

@Component({
  selector: 'app-sold-dishes-report',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, MatIconModule, RouterLink, DataTableComponent],
  template: `
    <main class="page list-page report-page">
      <section class="heading"><div><p>{{ georgian() ? 'ანალიტიკა' : 'ANALYTICS' }}</p><h1>{{ georgian() ? 'გაყიდული კერძები' : 'Sold dishes' }}</h1><span>{{ georgian() ? 'მხოლოდ დახურული ჩეკები' : 'Closed cheques only' }}</span></div><a routerLink="/analytics"><mat-icon>receipt_long</mat-icon>{{ georgian() ? 'ჩეკები' : 'Cheques' }}</a></section>
      <app-data-table>
        <section data-table-filters class="filters">
          <select [(ngModel)]="businessDayId" (ngModelChange)="onBusinessDayChange()"><option value="">{{ georgian() ? 'მიმდინარე სამუშაო დღე' : 'Current business day' }}</option><option value="all">{{ georgian() ? 'ყველა სამუშაო დღე' : 'All business days' }}</option>@for(day of filters().businessDays;track day.id){<option [value]="day.id">{{ formatDate(day.businessDate) }} · {{ day.status === 'OPEN' ? (georgian() ? 'ღია' : 'Open') : (georgian() ? 'დახურული' : 'Closed') }}</option>}</select>
          <label><span>{{ georgian() ? 'პერიოდი' : 'Period' }}</span><input type="date" [(ngModel)]="from" (ngModelChange)="onDateChange()" /></label>
          <label><span>{{ georgian() ? 'მდე' : 'To' }}</span><input type="date" [(ngModel)]="to" (ngModelChange)="onDateChange()" /></label>
          <button class="export" type="button" [disabled]="loading() || !report().items.length" (click)="export()"><mat-icon>download</mat-icon>{{ georgian() ? 'Excel ექსპორტი' : 'Export Excel' }}</button>
        </section>
        <section data-table-rows class="table-shell">
          <div class="summary">
            <div><span>{{ georgian() ? 'ჩეკები' : 'Cheques' }}</span><b>{{ report().summary.chequeCount }}</b></div><div><span>{{ georgian() ? 'ბრუნვა დღგ-ით' : 'Gross incl. VAT' }}</span><b>{{ amount(report().summary.subtotal) }}</b></div><div><span>{{ georgian() ? 'ფასდაკლება' : 'Discount' }}</span><b>{{ amount(report().summary.discount) }}</b></div><div><span>{{ georgian() ? 'მომსახურება' : 'Service fee' }}</span><b>{{ amount(report().summary.serviceFee) }}</b></div><div class="total"><span>{{ georgian() ? 'სულ დღგ-ით' : 'Total incl. VAT' }}</span><b>{{ amount(report().summary.total) }}</b></div>
          </div>
          <div class="table-head"><span>{{ georgian() ? 'თარიღი' : 'Date' }}</span><span>{{ georgian() ? 'კერძი' : 'Dish' }}</span><span>{{ georgian() ? 'რაოდენობა' : 'Qty' }}</span><span>{{ georgian() ? 'ერთ. ფასი' : 'Unit price' }}</span><span>{{ georgian() ? 'ბრუნვა დღგ-ით' : 'Gross incl. VAT' }}</span><span>{{ georgian() ? 'ფასდაკლება' : 'Discount' }}</span><span>{{ georgian() ? 'მომსახურება' : 'Service fee' }}</span><span>{{ georgian() ? 'სულ დღგ-ით' : 'Total incl. VAT' }}</span><span>{{ georgian() ? 'დღგ' : 'VAT' }}</span><span>{{ georgian() ? 'სულ დღგ-ის გარეშე' : 'Total excl. VAT' }}</span></div>
          @if(loading()){<div class="state">{{ georgian() ? 'იტვირთება...' : 'Loading...' }}</div>} @else if(error()){<div class="state"><span>{{ georgian() ? 'რეპორტის ჩატვირთვა ვერ მოხერხდა' : 'Could not load report' }}</span><button type="button" (click)="load()">{{ georgian() ? 'თავიდან ცდა' : 'Retry' }}</button></div>} @else {@for(row of report().items;track row.businessDate + row.dishId){<article><span>{{ row.businessDate }}</span><span class="dish"><b>{{ row.dishName }}</b><small>{{ row.dishId }}</small></span><b>{{ row.quantity }}</b><b>{{ amount(row.unitPrice) }}</b><b>{{ amount(row.grossAmount) }}</b><span>{{ amount(row.discountAmount) }}</span><span>{{ amount(row.serviceFeeAmount) }}</span><b>{{ amount(row.totalAmount) }}</b><span>{{ row.vatRate }}% · {{ amount(row.vatAmount) }}</span><b>{{ amount(row.amountExcludingVat) }}</b></article>}@empty{<div class="state">{{ georgian() ? 'დახურული ჩეკების გაყიდვები ვერ მოიძებნა' : 'No closed-cheque sales found' }}</div>}}</section>
        <footer data-table-footer><span>{{ report().items.length }} {{ georgian() ? 'სტრიქონი' : 'rows' }}</span><span class="payments">{{ georgian() ? 'გადახდები:' : 'Payments:' }} {{ georgian() ? 'ნაღდი' : 'Cash' }} {{ paymentTotal('cash') }} · {{ georgian() ? 'ბარათი' : 'Card' }} {{ paymentTotal('card') }} · {{ georgian() ? 'გადარიცხვა' : 'Transfer' }} {{ paymentTotal('transfer') }}</span></footer>
      </app-data-table>
    </main>`,
  styles: `.page{min-height:calc(100dvh - 56px);padding:22px 28px;background:var(--color-background)}.heading{display:flex;align-items:start;justify-content:space-between;margin-bottom:16px}.heading p{margin:0;color:var(--olive);font-size:12px;font-weight:800;letter-spacing:.1em}.heading h1{margin:3px 0;color:var(--text-primary);font-size:30px;letter-spacing:-.04em}.heading span{color:var(--text-muted);font-size:14px}.heading a,.export{display:flex;align-items:center;gap:6px;height:34px;padding:0 12px;border:1px solid var(--border);border-radius:8px;background:var(--surface-card);color:var(--olive);font-size:13px;font-weight:800;text-decoration:none}.heading mat-icon,.export mat-icon{width:17px;height:17px;font-size:17px}.filters{display:flex;flex-wrap:wrap;gap:8px}.filters label,.filters select{height:34px;border:1px solid var(--border);border-radius:8px;background:var(--surface-card);color:var(--text-primary);font-size:13px}.filters label{display:flex;align-items:center;gap:5px;padding:0 9px;color:var(--text-muted)}.filters label span{font-weight:700}.filters input{height:100%;border:0;background:transparent;color:var(--text-primary);outline:0}.filters select{min-width:190px;padding:0 8px}.export{margin-left:auto;border:0;background:var(--olive);color:#fff}.export:disabled{opacity:.45}.table-shell{overflow:auto}.summary{display:grid;grid-template-columns:repeat(5,minmax(150px,1fr));gap:1px;min-width:1000px;background:var(--border)}.summary div{display:grid;gap:3px;padding:11px 14px;background:var(--surface-card)}.summary span{color:var(--text-muted);font-size:12px}.summary b{color:var(--text-primary);font-size:17px}.summary .total b{color:var(--olive)}.table-head,article{display:grid;grid-template-columns:.8fr 1.7fr .55fr .75fr 1fr .82fr .85fr 1fr .95fr 1.1fr;align-items:center;min-width:1240px;min-height:51px;padding:0 14px;gap:8px}.table-head{position:sticky;top:0;z-index:2;min-height:39px;border-top:1px solid var(--border);background:var(--surface-muted);color:var(--text-muted);font-size:12px;font-weight:800}article{border-top:1px solid var(--border);color:var(--text-muted);font-size:13px}article b{color:var(--text-primary);font-size:13px}.dish{display:grid;gap:2px}.dish small{overflow:hidden;color:var(--text-muted);font-size:10px;text-overflow:ellipsis;white-space:nowrap}.state{display:grid;min-height:170px;place-items:center;gap:10px;padding:24px;color:var(--text-muted);text-align:center}.state button{padding:7px 11px;border:1px solid var(--border);border-radius:7px;background:var(--surface-card);color:var(--text-primary)}footer{display:flex;align-items:center;gap:18px;min-height:38px;padding:0 14px;border-top:1px solid var(--border);color:var(--text-muted);font-size:13px}.payments{margin-left:auto}@media(max-width:850px){.page{padding:16px}.heading{align-items:center}.heading h1{font-size:24px}.heading p,.heading span{display:none}.filters select{width:100%}.filters label{flex:1}.export{margin-left:0}.payments{display:none}}`,
})
export class SoldDishesReportComponent {
  private readonly api = inject(AdminApiService); readonly language = inject(LanguageService);
  readonly georgian = computed(() => this.language.current() === 'ka'); readonly filters = signal<ChequeAnalyticsFilters>(EMPTY_FILTERS); readonly report = signal<SoldDishReport>(EMPTY_REPORT); readonly loading = signal(true); readonly error = signal(false);
  businessDayId = ''; from = ''; to = '';
  constructor(){ this.api.getChequeAnalyticsFilters().subscribe({ next: filters => { this.filters.set(filters); this.businessDayId = filters.defaultBusinessDayId ?? ''; this.load(); }, error: () => this.load() }); }
  onBusinessDayChange(){ if(this.businessDayId !== 'all') { this.from=''; this.to=''; } this.load(); }
  onDateChange(){ if(this.from || this.to) this.businessDayId='all'; this.load(); }
  load(){ this.loading.set(true); this.error.set(false); this.api.getSoldDishAnalytics(this.query()).subscribe({next: report=>{this.report.set(report);this.loading.set(false)},error:()=>{this.loading.set(false);this.error.set(true)}}); }
  export(){ this.api.exportSoldDishAnalytics(this.query()).subscribe({next: blob=>{const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='meno-sold-dishes.xlsx';link.click();URL.revokeObjectURL(url);}}); }
  private query(): SoldDishAnalyticsQuery { return { businessDayId: this.businessDayId || undefined, from: this.from || undefined, to: this.to || undefined }; }
  amount(value:number){return value.toFixed(2)} paymentTotal(key:'cash'|'card'|'transfer'){return this.amount(this.report().payments.reduce((sum,row)=>sum+row[key],0))} formatDate(value:string){return new Intl.DateTimeFormat(this.georgian()?'ka-GE':'en-GB',{dateStyle:'medium'}).format(new Date(value));}
}
