import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AdminApiService, PinResult, Role, Staff } from '../../core/api/admin-api.service';

@Component({
  selector: 'app-staff', imports: [FormsModule],
  template: `<main class="page"><header><div><p>TEAM ACCESS</p><h1>Staff & PINs</h1></div><button (click)="create()">Add staff member</button></header><section class="form"><input placeholder="First name" [(ngModel)]="form.firstName"><input placeholder="Last name" [(ngModel)]="form.lastName"><input placeholder="Email" [(ngModel)]="form.email"><input placeholder="Phone" [(ngModel)]="form.phone"><select multiple [(ngModel)]="form.roleIds">@for(role of roles();track role.id){<option [value]="role.id">{{role.name}}</option>}</select></section>@if(pinResult()){<aside><strong>Generated PIN: {{pinResult()!.generatedPin}}</strong><span>Mock {{pinResult()!.mockDelivery.type}} delivery to {{pinResult()!.mockDelivery.destination}}</span></aside>}<section class="list">@for(member of staff();track member.id){<article [class.inactive]="!member.isActive"><div><strong>{{member.firstName}} {{member.lastName}}</strong><span>{{member.email || member.phone}}</span><small>{{roleNames(member)}}</small></div><div class="actions"><button (click)="reset(member.id)">Reset PIN</button><button (click)="reset(member.id,true)">Resend PIN</button><button (click)="disable(member.id)" [disabled]="!member.isActive">Disable</button></div></article>}@empty{<p>No staff members yet.</p>}</section></main>`,
  styles: `.page{padding:28px;max-width:1100px}header{display:flex;justify-content:space-between;align-items:center}header p{margin:0;color:var(--olive);font-size:12px;font-weight:800}h1{margin:4px 0 20px}button{border:0;border-radius:8px;padding:10px 14px;background:var(--olive);color:#fff;font-weight:800}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:16px;border:1px solid var(--border);border-radius:13px;background:var(--surface-card)}input,select{min-height:42px;padding:0 10px;border:1px solid var(--border);border-radius:8px;background:var(--surface-muted);color:var(--text-primary)}select{height:88px}aside{display:grid;gap:5px;margin:14px 0;padding:14px;border-radius:10px;background:#e8f3e7;color:#184e28}.list{display:grid;gap:10px;margin-top:18px}article{display:flex;justify-content:space-between;gap:16px;padding:15px;border:1px solid var(--border);border-radius:12px;background:var(--surface-card)}article div:first-child{display:grid;gap:3px}article span,article small{color:var(--text-muted)}.actions{display:flex;gap:7px;align-items:center}.actions button{background:var(--surface-muted);color:var(--text-primary);border:1px solid var(--border)}.inactive{opacity:.55}@media(max-width:700px){.page{padding:18px}.form{grid-template-columns:1fr}article{align-items:flex-start;flex-direction:column}.actions{flex-wrap:wrap}}`,
})
export class StaffComponent {
  private readonly api=inject(AdminApiService); readonly staff=signal<Staff[]>([]); readonly roles=signal<Role[]>([]); readonly pinResult=signal<PinResult|null>(null);
  form={firstName:'',lastName:'',email:'',phone:'',roleIds:[] as string[]};
  constructor(){this.load();}
  load(){this.api.getStaff().subscribe({next:value=>this.staff.set(value)});this.api.getRoles().subscribe({next:value=>this.roles.set(value)});}
  create(){if(!this.form.firstName||!this.form.lastName||(!this.form.email&&!this.form.phone))return;this.api.createStaff({firstName:this.form.firstName,lastName:this.form.lastName,email:this.form.email||undefined,phone:this.form.phone||undefined,roleIds:this.form.roleIds}).subscribe({next:value=>{this.pinResult.set(value);this.form={firstName:'',lastName:'',email:'',phone:'',roleIds:[]};this.load();}});}
  reset(staffId:string,resend=false){this.api.resetPin(staffId,resend).subscribe({next:value=>this.pinResult.set(value)});}
  disable(staffId:string){this.api.deleteStaff(staffId).subscribe({next:()=>this.load()});}
  roleNames(member:Staff){return member.roles.map((role)=>role.name).join(', ')||'No role';}
}
